coverage:
  range: "0...100"
  status:
    patch:
      default:
        informational: true
    project:
      default:
        informational: true
fixes:
  - "engine/::game/engine/" # eg. remaps `engine/Scene.lua` to `game/engine/Scene.lua`
  - "arpg/::game/arpg/"
