language: c
compiler: clang

addons:
  apt:
    packages:
      - luajit

before_script:
  - cd $TRAVIS_BUILD_DIR/source/code/beryl
  - make
  - LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/source/code/beryl:$LD_LIBRARY_PATH
  - export LD_LIBRARY_PATH

script:
  - cd $TRAVIS_BUILD_DIR/game
  - luajit-2.0.0-beta9 Tests.lua
