-- local Features = require("dev/Features");

-- if Features.testing then
-- 	local luacov;
-- 	if Features.codeCoverage then
-- 		luacov = require("external/luacov/runner");
-- 		local luacovExcludes = { "assets/.*$", "^main$", "Test", "test" };
-- 		luacov.init({ runreport = true, exclude = luacovExcludes });
-- 	end
-- 	local engine = Engine:new(true);
-- 	local TestSuite = require("dev/TestSuite");
-- 	local success = TestSuite:execute();
-- 	engine:quit();
-- 	if luacov then
-- 		luacov.shutdown();
-- 	end
-- 	local exitCode = success and 0 or 1;
-- 	love.run = function()
-- 		return function()
-- 			return exitCode;
-- 		end
-- 	end
-- end
