local DamageScalingSources = {
	ATTACKER_OFFENSE_PHYSICAL = 1,
	ATTACKER_OFFENSE_MAGIC = 1,
	ATTACKER_MAX_HEALTH = 3,
	ATTACKER_CURRENT_HEALTH = 4,
	ATTACKER_MISSING_HEALTH = 5,

	VICTIM_MAX_HEALTH = 6,
	VICTIM_CURRENT_HEALTH = 7,
	VICTIM_MISSING_HEALTH = 8,
};

return DamageScalingSources;
