name: Build

on:
  pull_request:
  push:

jobs:
  tests-windows:
    name: Run Tests (Windows)
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add vcvars location to path
      run: echo "##[add-path]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build"
    - name: Install Love 2D
      run:  |
        curl -L -o love.zip https://bitbucket.org/rude/love/downloads/love-11.3-win64.zip
        unzip love.zip
        cp .\love-11.3-win64\love.exe .\love.exe
    - name: Install Meson
      run:  |
        curl -L -o meson.msi https://github.com/mesonbuild/meson/releases/download/0.53.1/meson-0.53.1-64.msi
        cmd /c start /wait msiexec.exe /i meson.msi /quiet
        echo "##[add-path]C:\Program Files\Meson"
    - name: Build Beryl
      run: .\build_beryl_windows.ps1
    - name: Run Tests
      run: love . /test
      working-directory: ./game

  tests-linux:
    name: Run Tests (Linux)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Love 2D
      run: sudo add-apt-repository -y ppa:bartbes/love-stable && sudo apt-get update && sudo apt-get install -y love
    - name: Install Meson
      run:  |
        sudo apt-get install python3 python3-pip python3-setuptools python3-wheel ninja-build
        sudo pip3 install meson
    - name: Build Beryl
      run: ./build_beryl_linux.sh
    - name: Run Tests
      run: love . /test
      working-directory: ./game
