name: Build

on:
  pull_request:
  push:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Love 2D
      run: sudo add-apt-repository -y ppa:bartbes/love-stable && sudo apt-get update && sudo apt-get install -y love
    - name: Install Meson Dependencies
      run:  sudo apt-get install python3 python3-pip python3-setuptools python3-wheel ninja-build
    - name: Install Meson
      run:  sudo pip3 install meson
    - name: Configure build directory
      run: CC=clang meson builddir --backend ninja --buildtype release
      working-directory: ./lib/
    - name: Build Beryl
      run: ninja
      working-directory: ./lib/builddir
    - name: Copy Beryl binaries
      run: cp ./lib/builddir/* ./game
    - name: Run Tests
      run: love . /test
      working-directory: ./game
