name: CI

on:
  push:
    branches:
      - main

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            lib/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: pyvista/setup-headless-display-action@v3
      - uses: cachix/install-nix-action@v31
      - uses: nicknovitski/nix-develop@v1
      - run: cargo build --release
        working-directory: lib
      - run: cp lib/target/release/libdiamond.so runtime/diamond.so
      - name: Run Lua Tests
        working-directory: runtime
        run: love . /test /coverage
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: llvm-tools-preview
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Gather coverage results
        working-directory: lib
        run: cargo llvm-cov --codecov --output-path codecov.json
      - name: Upload Results
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lib/codecov.json, runtime/luacov.report.out
          fail_ci_if_error: true
          verbose: true

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            lib/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: pyvista/setup-headless-display-action@v3
      - name: Download Love
        run: |
          $zip = New-TemporaryFile
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://github.com/love2d/love/releases/download/11.4/love-11.4-win64.zip" -OutFile $zip
          Expand-Archive $zip -DestinationPath "bin" -Force
          Remove-Item $zip
          Get-ChildItem -Path "bin" -Recurse -File | Move-Item -Destination "bin"
          Get-ChildItem -Path "bin" -Recurse -Directory | Remove-Item
      - run: cargo build --release
        working-directory: lib
      - run: cp lib\target\release\diamond.dll bin\diamond.dll
      - name: Run Lua Tests
        working-directory: runtime
        run: ..\bin\lovec.exe . /test /coverage
      - run: cargo test
        working-directory: lib
