name: CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Run Tests
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Mesa
        run: |
          curl.exe -L --output mesa.7z --url https://github.com/pal1000/mesa-dist-win/releases/download/22.3.4/mesa3d-22.3.4-release-msvc.7z
          & "C:\Program Files\7-Zip\7z.exe" x mesa.7z
          $setup_script = Get-Content -Path systemwidedeploy.cmd
          $setup_script = $setup_script -replace '^.*deployment choice.*$', '@GOTO desktopgl'
          $setup_script = $setup_script -replace '^.*deploy complete.*$', '@exit'
          $setup_script | Set-Content -Path systemwidedeploy.cmd
          cmd /c systemwidedeploy.cmd
      - name: Install Love2D
        shell: bash
        run: |
          curl -L -o love.zip https://github.com/love2d/love/releases/download/11.3/love-11.3-win64.zip
          unzip love.zip
          echo "${{ github.workspace }}\love-11.3-win64" >> $GITHUB_PATH
      - name: Build native libs
        run: .\build_libs_windows.ps1
      - name: Run Rust tests
        run: cargo test --release
        working-directory: lib
      - name: Run Lua tests
        run: lovec . /test-unit /test-gfx
        working-directory: game
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-output
          path: game/test-output
