name: CI

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Run Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            lib/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Setup headless display
        uses: pyvista/setup-headless-display-action@v3
        with:
          pyvista: false
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: llvm-tools-preview
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Download Love
        run: |
          $zip = New-TemporaryFile
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://github.com/love2d/love/releases/download/11.5/love-11.5-win64.zip" -OutFile $zip
          Expand-Archive $zip -DestinationPath "bin" -Force
          Remove-Item $zip
          Get-ChildItem -Path "bin" -Recurse -File | Move-Item -Destination "bin"
          Get-ChildItem -Path "bin" -Recurse -Directory | Remove-Item
      - run: cargo build --release
        working-directory: lib
      - run: cp lib\target\release\diamond.dll bin\diamond.dll
      - name: Run Lua tests
        run: ..\bin\lovec.exe . /test /coverage
        working-directory: runtime
      - name: Fix line endings in Lua coverage report
        run: (Get-Content -raw luacov.report.out) -replace "`r`n","`n" | Set-Content -nonewline luacov.report.out
        working-directory: runtime      
      - name: Run Rust tests
        run: cargo llvm-cov --codecov --output-path codecov.json
        working-directory: lib
      - name: Upload Results
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lib/codecov.json, runtime/luacov.report.out
          fail_ci_if_error: true
          verbose: true