name: Test Coverage

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Measure Test Coverage
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Mesa
        run: |
          curl.exe -L --output mesa.7z --url https://github.com/pal1000/mesa-dist-win/releases/download/22.3.4/mesa3d-22.3.4-release-msvc.7z
          "C:\Program Files\7-Zip\7z.exe" x mesa.7z
          Move-Item -Path x64/opengl32.dll -Destination game/opengl32.dll
          Move-Item -Path x64/libglapi.dll -Destination game/libglapi.dll
        working-directory: game
      - name: Install Love2D
        shell: bash
        run: |
          curl -L -o love.zip https://github.com/love2d/love/releases/download/11.3/love-11.3-win64.zip
          unzip love.zip
          echo "${{ github.workspace }}\love-11.3-win64" >> $GITHUB_PATH
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: llvm-tools-preview
      - name: Install grcov
        run: cargo install grcov
      - name: Run native tests
        run: cargo test --no-fail-fast
        working-directory: lib
        env:
          RUSTFLAGS: "-Cinstrument-coverage"
      - name: Gather native coverage results
        run: >
          grcov
          .
          -s .
          -t lcov
          -o coverage.txt
          --llvm
          --branch
          --ignore-not-existing
          --keep-only */src/**
          --binary-path ./target/debug
          --excl-line "#\[derive\("
          --excl-br-line "#\[derive\("
          --excl-start "mod tests \{"
          --excl-br-start "mod tests \{"
        working-directory: lib
      - name: Run Lua Tests
        run: lovec . /test-unit /test-gfx /coverage
        working-directory: game
      - name: Upload Results
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          path_to_write_report: codecov_report.txt
          verbose: true
      - uses: actions/upload-artifact@v2
        with:
          name: codecov_report
          path: codecov_report.txt
