name: Test Coverage

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Measure Test Coverage
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Mesa
        run: |
          curl.exe -L --output mesa.7z --url https://github.com/pal1000/mesa-dist-win/releases/download/22.3.4/mesa3d-22.3.4-release-msvc.7z
          & "C:\Program Files\7-Zip\7z.exe" x mesa.7z
          $setup_script = Get-Content -Path systemwidedeploy.cmd
          $setup_script = $setup_script -replace '^.*deployment choice.*$', '@GOTO desktopgl'
          $setup_script = $setup_script -replace '^.*deploy complete.*$', '@exit'
          $setup_script | Set-Content -Path systemwidedeploy.cmd
          cmd /c systemwidedeploy.cmd
      - name: Build
        run: .\build.ps1
      - name: Run Lua Tests
        run: ..\bin\lovec.exe . /test-unit /test-gfx /coverage
        working-directory: game
      - name: Fix line endings in Lua coverage report
        run: (Get-Content -raw luacov.report.out) -replace "`r`n","`n" | Set-Content -nonewline luacov.report.out
        working-directory: game
      - name: Install Rust toolchain with coverage tooling
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: llvm-tools-preview
      - name: Install grcov
        run: cargo install grcov
      - name: Run native tests
        run: cargo test --no-fail-fast
        working-directory: lib
        env:
          RUSTFLAGS: "-Cinstrument-coverage"
      - name: Gather native coverage results
        run: >
          grcov
          .
          -s .
          -t lcov
          -o coverage.txt
          --llvm
          --branch
          --ignore-not-existing
          --keep-only */src/**
          --binary-path ./target/debug
          --excl-line "#\[derive\("
          --excl-br-line "#\[derive\("
          --excl-start "mod tests \{"
          --excl-br-start "mod tests \{"
        working-directory: lib
      - name: Upload Results
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          verbose: true
